import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { Allura } from 'next/font/google';
import Navbar from "@/ui/Navbar/Navbar";

const allura = Allura({
  subsets: ['latin'],
  weight: ['400']
})

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={allura.className}>
        <Navbar/>
        {children}
      </body>
    </html>
  );
}
