import type { Metadata } from "next";
import {
    Caveat,
    Ephesis,
    Italianno,
    MonteCarlo,
    Parisienne,
    Petit_Formal_Script,
    Tangerine,
    Vujahday_Script
} from "next/font/google";
import "./globals.css";

const italianno = Petit_Formal_Script({ subsets: ["latin"], weight: ["400"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import Navbar from "@/ui/Navbar/Navbar";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={italianno.className}>
        {children}
      </body>
    </html>
  );
}
